### PR TITLE
started french translation

### PR DESCRIPTION
**Pull request by cherrykoda**
40% complete

### CODE REVIEW

**Comment by coderkun** [comment]
@Nightarrow85 that’s great, thanks a lot. Do you want to me wait until the translation is complete or merge already?

**Comment by cherrykoda** [comment]
Totally up to you, admittedly I needed the pull-request for hacktoberfest,
but I am still working on this for you guys.

Thanks!

**Comment by coderkun** [comment]
@Nightarrow85, do you mind putting your or none e‑mail address in the “Language-Team” field (of file `locale/fr_FR/LC_MESSAGES/The Legend of Z.po`)?
Thanks a lot for your work!

**Comment by cherrykoda** [comment]
Added my email to the "Language-Team" field, more work getting done this week on this. 
Thanks!

**Pull request closed without merging**
